spring:
  datasource:
    url: jdbc:mysql://localhost:3306/UsersDB
    username: root
    password: evgeniy29
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: MySql
    database-platform: org.hibernate.dialect.MySqlDialect
    show-sql: false
    properties:
      hibernate:
        format-sql: true






